use crate::settings::DisplayLayout;
use qmk_via_api::keycodes::Keycode;

pub fn base_char(layout: DisplayLayout, keycode_bytes: u16) -> Option<&'static str> {
    let keycode = Keycode::try_from(keycode_bytes).ok()?;
    match layout {
        DisplayLayout::Us => None,
        DisplayLayout::German => german_base_char(keycode),
        DisplayLayout::French => french_base_char(keycode),
        DisplayLayout::Italian => italian_base_char(keycode),
        DisplayLayout::Spanish => spanish_base_char(keycode),
    }
}

pub fn shifted_char(layout: DisplayLayout, keycode_bytes: u16) -> Option<&'static str> {
    let keycode = Keycode::try_from(keycode_bytes).ok()?;
    match layout {
        DisplayLayout::Us => None,
        DisplayLayout::German => german_shifted_char(keycode),
        DisplayLayout::French => french_shifted_char(keycode),
        DisplayLayout::Italian => italian_shifted_char(keycode),
        DisplayLayout::Spanish => spanish_shifted_char(keycode),
    }
}

pub fn altgr_char(layout: DisplayLayout, keycode_bytes: u16) -> Option<&'static str> {
    let keycode = Keycode::try_from(keycode_bytes).ok()?;
    match layout {
        DisplayLayout::Us => None,
        DisplayLayout::German => german_altgr_char(keycode),
        DisplayLayout::French => french_altgr_char(keycode),
        DisplayLayout::Italian => italian_altgr_char(keycode),
        DisplayLayout::Spanish => spanish_altgr_char(keycode),
    }
}

fn german_base_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_Y => Some("Z"),
        Keycode::KC_Z => Some("Y"),
        Keycode::KC_MINUS => Some("ß"),
        Keycode::KC_EQUAL => Some("´"),
        Keycode::KC_LEFT_BRACKET => Some("Ü"),
        Keycode::KC_RIGHT_BRACKET => Some("+"),
        Keycode::KC_SEMICOLON => Some("Ö"),
        Keycode::KC_QUOTE => Some("Ä"),
        Keycode::KC_BACKSLASH => Some("#"),
        Keycode::KC_NONUS_HASH => Some("#"),
        Keycode::KC_NONUS_BACKSLASH => Some("<"),
        Keycode::KC_SLASH => Some("-"),
        Keycode::KC_GRAVE => Some("^"),
        _ => None,
    }
}

fn german_shifted_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_2 => Some("\""),
        Keycode::KC_3 => Some("§"),
        Keycode::KC_6 => Some("&"),
        Keycode::KC_7 => Some("/"),
        Keycode::KC_8 => Some("("),
        Keycode::KC_9 => Some(")"),
        Keycode::KC_0 => Some("="),
        Keycode::KC_MINUS => Some("?"),
        Keycode::KC_EQUAL => Some("`"),
        Keycode::KC_RIGHT_BRACKET => Some("*"),
        Keycode::KC_BACKSLASH => Some("'"),
        Keycode::KC_NONUS_HASH => Some("'"),
        Keycode::KC_NONUS_BACKSLASH => Some(">"),
        Keycode::KC_COMMA => Some(";"),
        Keycode::KC_DOT => Some(":"),
        Keycode::KC_SLASH => Some("_"),
        Keycode::KC_GRAVE => Some("°"),
        _ => None,
    }
}

fn german_altgr_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_1 => Some("¹"),
        Keycode::KC_2 => Some("²"),
        Keycode::KC_3 => Some("³"),
        Keycode::KC_4 => Some("¼"),
        Keycode::KC_5 => Some("½"),
        Keycode::KC_6 => Some("¬"),
        Keycode::KC_7 => Some("{"),
        Keycode::KC_8 => Some("["),
        Keycode::KC_9 => Some("]"),
        Keycode::KC_0 => Some("}"),
        Keycode::KC_MINUS => Some("\\"),
        Keycode::KC_RIGHT_BRACKET => Some("~"),
        Keycode::KC_BACKSLASH => Some("’"),
        Keycode::KC_NONUS_HASH => Some("’"),
        Keycode::KC_NONUS_BACKSLASH => Some("|"),
        Keycode::KC_COMMA => Some("·"),
        Keycode::KC_DOT => Some("…"),
        Keycode::KC_SLASH => Some("–"),
        Keycode::KC_Q => Some("@"),
        Keycode::KC_W => Some("ł"),
        Keycode::KC_E => Some("€"),
        Keycode::KC_R => Some("¶"),
        Keycode::KC_T => Some("ŧ"),
        Keycode::KC_Y => Some("←"),
        Keycode::KC_U => Some("↓"),
        Keycode::KC_I => Some("→"),
        Keycode::KC_O => Some("ø"),
        Keycode::KC_P => Some("þ"),
        Keycode::KC_A => Some("æ"),
        Keycode::KC_D => Some("ð"),
        Keycode::KC_F => Some("đ"),
        Keycode::KC_G => Some("ŋ"),
        Keycode::KC_H => Some("ħ"),
        Keycode::KC_K => Some("ĸ"),
        Keycode::KC_L => Some("ł"),
        Keycode::KC_Z => Some("»"),
        Keycode::KC_X => Some("«"),
        Keycode::KC_C => Some("¢"),
        Keycode::KC_V => Some("„"),
        Keycode::KC_B => Some("“"),
        Keycode::KC_N => Some("”"),
        Keycode::KC_M => Some("µ"),
        _ => None,
    }
}

fn french_base_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_1 => Some("&"),
        Keycode::KC_2 => Some("é"),
        Keycode::KC_3 => Some("\""),
        Keycode::KC_4 => Some("'"),
        Keycode::KC_5 => Some("("),
        Keycode::KC_6 => Some("-"),
        Keycode::KC_7 => Some("è"),
        Keycode::KC_8 => Some("_"),
        Keycode::KC_9 => Some("ç"),
        Keycode::KC_0 => Some("à"),
        Keycode::KC_MINUS => Some(")"),
        Keycode::KC_LEFT_BRACKET => Some("^"),
        Keycode::KC_RIGHT_BRACKET => Some("$"),
        Keycode::KC_GRAVE => Some("²"),
        Keycode::KC_BACKSLASH => Some("*"),
        Keycode::KC_NONUS_HASH => Some("*"),
        Keycode::KC_NONUS_BACKSLASH => Some("<"),
        Keycode::KC_Q => Some("A"),
        Keycode::KC_W => Some("Z"),
        Keycode::KC_A => Some("Q"),
        Keycode::KC_Z => Some("W"),
        Keycode::KC_SEMICOLON => Some("M"),
        Keycode::KC_QUOTE => Some("ù"),
        Keycode::KC_M => Some(","),
        Keycode::KC_COMMA => Some(";"),
        Keycode::KC_DOT => Some(":"),
        Keycode::KC_SLASH => Some("!"),
        _ => None,
    }
}

fn french_shifted_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_1 => Some("1"),
        Keycode::KC_2 => Some("2"),
        Keycode::KC_3 => Some("3"),
        Keycode::KC_4 => Some("4"),
        Keycode::KC_5 => Some("5"),
        Keycode::KC_6 => Some("6"),
        Keycode::KC_7 => Some("7"),
        Keycode::KC_8 => Some("8"),
        Keycode::KC_9 => Some("9"),
        Keycode::KC_0 => Some("0"),
        Keycode::KC_MINUS => Some("°"),
        Keycode::KC_LEFT_BRACKET => Some("¨"),
        Keycode::KC_RIGHT_BRACKET => Some("£"),
        Keycode::KC_GRAVE => Some("~"),
        Keycode::KC_BACKSLASH => Some("µ"),
        Keycode::KC_NONUS_HASH => Some("µ"),
        Keycode::KC_NONUS_BACKSLASH => Some(">"),
        Keycode::KC_QUOTE => Some("%"),
        Keycode::KC_M => Some("?"),
        Keycode::KC_COMMA => Some("."),
        Keycode::KC_DOT => Some("/"),
        Keycode::KC_SLASH => Some("§"),
        _ => None,
    }
}

fn french_altgr_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_1 => Some("¹"),
        Keycode::KC_2 => Some("~"),
        Keycode::KC_3 => Some("#"),
        Keycode::KC_4 => Some("{"),
        Keycode::KC_5 => Some("["),
        Keycode::KC_6 => Some("|"),
        Keycode::KC_7 => Some("`"),
        Keycode::KC_8 => Some("\\"),
        Keycode::KC_9 => Some("^"),
        Keycode::KC_0 => Some("@"),
        Keycode::KC_MINUS => Some("]"),
        Keycode::KC_EQUAL => Some("}"),
        Keycode::KC_RIGHT_BRACKET => Some("¤"),
        Keycode::KC_GRAVE => Some("¬"),
        Keycode::KC_NONUS_BACKSLASH => Some("|"),
        Keycode::KC_COMMA => Some("•"),
        Keycode::KC_DOT => Some("·"),
        Keycode::KC_Q => Some("æ"),
        Keycode::KC_W => Some("«"),
        Keycode::KC_E => Some("€"),
        Keycode::KC_R => Some("¶"),
        Keycode::KC_T => Some("ŧ"),
        Keycode::KC_Y => Some("←"),
        Keycode::KC_U => Some("↓"),
        Keycode::KC_I => Some("→"),
        Keycode::KC_O => Some("ø"),
        Keycode::KC_P => Some("þ"),
        Keycode::KC_A => Some("@"),
        Keycode::KC_S => Some("ß"),
        Keycode::KC_D => Some("ð"),
        Keycode::KC_F => Some("đ"),
        Keycode::KC_G => Some("ŋ"),
        Keycode::KC_H => Some("ħ"),
        Keycode::KC_K => Some("ĸ"),
        Keycode::KC_L => Some("ł"),
        Keycode::KC_Z => Some("ł"),
        Keycode::KC_X => Some("»"),
        Keycode::KC_C => Some("¢"),
        Keycode::KC_V => Some("„"),
        Keycode::KC_B => Some("“"),
        Keycode::KC_N => Some("”"),
        Keycode::KC_SEMICOLON => Some("µ"),
        _ => None,
    }
}

fn italian_base_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_MINUS => Some("'"),
        Keycode::KC_EQUAL => Some("ì"),
        Keycode::KC_LEFT_BRACKET => Some("è"),
        Keycode::KC_RIGHT_BRACKET => Some("+"),
        Keycode::KC_QUOTE => Some("à"),
        Keycode::KC_GRAVE => Some("\\"),
        Keycode::KC_BACKSLASH => Some("ù"),
        Keycode::KC_NONUS_HASH => Some("ù"),
        Keycode::KC_NONUS_BACKSLASH => Some("<"),
        Keycode::KC_SLASH => Some("-"),
        Keycode::KC_SEMICOLON => Some("ò"),
        _ => None,
    }
}

fn italian_shifted_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_2 => Some("\""),
        Keycode::KC_3 => Some("£"),
        Keycode::KC_6 => Some("&"),
        Keycode::KC_7 => Some("/"),
        Keycode::KC_8 => Some("("),
        Keycode::KC_9 => Some(")"),
        Keycode::KC_0 => Some("="),
        Keycode::KC_MINUS => Some("?"),
        Keycode::KC_EQUAL => Some("^"),
        Keycode::KC_LEFT_BRACKET => Some("é"),
        Keycode::KC_RIGHT_BRACKET => Some("*"),
        Keycode::KC_QUOTE => Some("°"),
        Keycode::KC_GRAVE => Some("|"),
        Keycode::KC_BACKSLASH => Some("§"),
        Keycode::KC_NONUS_HASH => Some("§"),
        Keycode::KC_NONUS_BACKSLASH => Some(">"),
        Keycode::KC_SEMICOLON => Some("ç"),
        Keycode::KC_COMMA => Some(";"),
        Keycode::KC_DOT => Some(":"),
        Keycode::KC_SLASH => Some("_"),
        _ => None,
    }
}

fn italian_altgr_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_1 => Some("¹"),
        Keycode::KC_2 => Some("²"),
        Keycode::KC_3 => Some("³"),
        Keycode::KC_4 => Some("¼"),
        Keycode::KC_5 => Some("½"),
        Keycode::KC_6 => Some("¬"),
        Keycode::KC_7 => Some("{"),
        Keycode::KC_8 => Some("["),
        Keycode::KC_9 => Some("]"),
        Keycode::KC_0 => Some("}"),
        Keycode::KC_MINUS => Some("`"),
        Keycode::KC_EQUAL => Some("~"),
        Keycode::KC_LEFT_BRACKET => Some("["),
        Keycode::KC_RIGHT_BRACKET => Some("]"),
        Keycode::KC_SEMICOLON => Some("@"),
        Keycode::KC_QUOTE => Some("#"),
        Keycode::KC_GRAVE => Some("¬"),
        Keycode::KC_NONUS_BACKSLASH => Some("«"),
        Keycode::KC_DOT => Some("·"),
        Keycode::KC_Q => Some("@"),
        Keycode::KC_W => Some("ł"),
        Keycode::KC_E => Some("€"),
        Keycode::KC_R => Some("¶"),
        Keycode::KC_T => Some("ŧ"),
        Keycode::KC_Y => Some("←"),
        Keycode::KC_U => Some("↓"),
        Keycode::KC_I => Some("→"),
        Keycode::KC_O => Some("ø"),
        Keycode::KC_P => Some("þ"),
        Keycode::KC_A => Some("æ"),
        Keycode::KC_S => Some("ß"),
        Keycode::KC_D => Some("ð"),
        Keycode::KC_F => Some("đ"),
        Keycode::KC_G => Some("ŋ"),
        Keycode::KC_H => Some("ħ"),
        Keycode::KC_K => Some("ĸ"),
        Keycode::KC_L => Some("ł"),
        Keycode::KC_Z => Some("«"),
        Keycode::KC_X => Some("»"),
        Keycode::KC_C => Some("¢"),
        Keycode::KC_V => Some("“"),
        Keycode::KC_B => Some("”"),
        Keycode::KC_N => Some("ñ"),
        Keycode::KC_M => Some("µ"),
        _ => None,
    }
}

fn spanish_base_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_MINUS => Some("'"),
        Keycode::KC_EQUAL => Some("¡"),
        Keycode::KC_LEFT_BRACKET => Some("`"),
        Keycode::KC_RIGHT_BRACKET => Some("+"),
        Keycode::KC_QUOTE => Some("´"),
        Keycode::KC_GRAVE => Some("º"),
        Keycode::KC_NONUS_BACKSLASH => Some("<"),
        Keycode::KC_SLASH => Some("-"),
        Keycode::KC_SEMICOLON => Some("Ñ"),
        Keycode::KC_BACKSLASH => Some("Ç"),
        Keycode::KC_NONUS_HASH => Some("Ç"),
        _ => None,
    }
}

fn spanish_shifted_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_2 => Some("\""),
        Keycode::KC_3 => Some("·"),
        Keycode::KC_6 => Some("&"),
        Keycode::KC_7 => Some("/"),
        Keycode::KC_8 => Some("("),
        Keycode::KC_9 => Some(")"),
        Keycode::KC_0 => Some("="),
        Keycode::KC_MINUS => Some("?"),
        Keycode::KC_EQUAL => Some("¿"),
        Keycode::KC_LEFT_BRACKET => Some("^"),
        Keycode::KC_RIGHT_BRACKET => Some("*"),
        Keycode::KC_QUOTE => Some("¨"),
        Keycode::KC_GRAVE => Some("ª"),
        Keycode::KC_NONUS_BACKSLASH => Some(">"),
        Keycode::KC_COMMA => Some(";"),
        Keycode::KC_DOT => Some(":"),
        Keycode::KC_SLASH => Some("_"),
        _ => None,
    }
}

fn spanish_altgr_char(keycode: Keycode) -> Option<&'static str> {
    match keycode {
        Keycode::KC_1 => Some("|"),
        Keycode::KC_2 => Some("@"),
        Keycode::KC_3 => Some("#"),
        Keycode::KC_4 => Some("~"),
        Keycode::KC_5 => Some("½"),
        Keycode::KC_6 => Some("¬"),
        Keycode::KC_7 => Some("{"),
        Keycode::KC_8 => Some("["),
        Keycode::KC_9 => Some("]"),
        Keycode::KC_0 => Some("}"),
        Keycode::KC_MINUS => Some("\\"),
        Keycode::KC_QUOTE => Some("{"),
        Keycode::KC_GRAVE => Some("\\"),
        Keycode::KC_RIGHT_BRACKET => Some("]"),
        Keycode::KC_NONUS_BACKSLASH => Some("|"),
        Keycode::KC_COMMA => Some("•"),
        Keycode::KC_DOT => Some("·"),
        Keycode::KC_Q => Some("@"),
        Keycode::KC_W => Some("ł"),
        Keycode::KC_E => Some("€"),
        Keycode::KC_R => Some("¶"),
        Keycode::KC_T => Some("ŧ"),
        Keycode::KC_Y => Some("←"),
        Keycode::KC_U => Some("↓"),
        Keycode::KC_I => Some("→"),
        Keycode::KC_O => Some("ø"),
        Keycode::KC_P => Some("þ"),
        Keycode::KC_A => Some("æ"),
        Keycode::KC_S => Some("ß"),
        Keycode::KC_D => Some("ð"),
        Keycode::KC_F => Some("đ"),
        Keycode::KC_G => Some("ŋ"),
        Keycode::KC_H => Some("ħ"),
        Keycode::KC_K => Some("ĸ"),
        Keycode::KC_L => Some("ł"),
        Keycode::KC_Z => Some("«"),
        Keycode::KC_X => Some("»"),
        Keycode::KC_C => Some("¢"),
        Keycode::KC_V => Some("„"),
        Keycode::KC_B => Some("“"),
        Keycode::KC_N => Some("”"),
        Keycode::KC_M => Some("µ"),
        _ => None,
    }
}
